"use strict";

function getRandomBelonging()
{
  return getRandomElement(kBelongings);
}

const kBelongings = [
  "Alchemical ingredients",
  "Amulet",
  "Antidote",
  "Armor",
  "Arrows",
  "Axe",
  "Backpack",
  "Bag",
  "Bandage",
  "Banner",
  "Barrel",
  "Belt",
  "Belt pouch",
  "Book",
  "Boots",
  "Bow",
  "Bracelet",
  "Breastplate",
  "Bridle",
  "Chainmail",
  "Chest",
  "Cloak",
  "Clothing",
  "Codex",
  "Coin purse",
  "Crate",
  "Crossbow",
  "Crown",
  "Dagger",
  "Diary",
  "Drum",
  "Earrings",
  "Elixir",
  "Flag",
  "Flute",
  "Gambeson",
  "Gauntlets",
  "Gemstone",
  "Gloves",
  "Greaves",
  "Grimoire",
  "Harp",
  "Hat",
  "Helmet",
  "Herbal remedy",
  "Hood",
  "Horn",
  "Horse",
  "Idol",
  "Inkpot",
  "Jewelry",
  "Journal",
  "Lance",
  "Lute",
  "Mace",
  "Musical instrument",
  "Necklace",
  "Oil",
  "Ointment",
  "Painting",
  "Pants",
  "Papyrus",
  "Parchment",
  "Perfume",
  "Plate armor",
  "Potion",
  "Potion of clarity",
  "Potion of courage",
  "Potion of endurance",
  "Potion of healing",
  "Potion of invisibility",
  "Potion of luck",
  "Potion of protection",
  "Potion of speed",
  "Potion of strength",
  "Potion of wisdom",
  "Potion vial",
  "Poultice",
  "Precious metal",
  "Quill",
  "Quiver",
  "Relic",
  "Ring",
  "Robe",
  "Sack",
  "Saddle",
  "Salve",
  "Scepter",
  "Scroll",
  "Scroll case",
  "Scroll of enchantment",
  "Scroll of fireball",
  "Scroll of invisibility",
  "Scroll of prophecy",
  "Scroll of summoning",
  "Scroll of teleportation",
  "Scroll of warding",
  "Sculpture",
  "Shield",
  "Shirt",
  "Shoes",
  "Spear",
  "Spellbook",
  "Splint",
  "Staff",
  "Sword",
  "Tabard",
  "Talisman",
  "Tapestry",
  "Tome",
  "Tonic",
  "Tool",
  "Toy",
  "Trinket",
  "Tunic",
  "Wand",
  "Weapon",
]
