"use strict";

function getRandomComplication()
{
  return getRandomElement(kComplications);
}

const kComplications = [
  "Addiction",
  "Amnesia",
  "Artificial Intelligence Rebellion",
  "Betrayal of Authority",
  "Betrayal of Confidence",
  "Betrayal of Duty",
  "Betrayal of Expectations",
  "Betrayal of Faith",
  "Betrayal of Family",
  "Betrayal of Friendship",
  "Betrayal of Honor",
  "Betrayal of Ideals",
  "Betrayal of Innocence",
  "Betrayal of Integrity",
  "Betrayal of Love",
  "Betrayal of Loyalty",
  "Betrayal of Nation",
  "Betrayal of Purpose",
  "Betrayal of Self",
  "Betrayal of Trust",
  "Betrayal of Truth",
  "Betrayal",
  "Blackmail",
  "Catastrophic Failure",
  "Civil Unrest",
  "Collapse of Society",
  "Conspiracies",
  "Corruption of Power",
  "Corruption",
  "Cultural Conflict",
  "Curse",
  "Deception",
  "Desperate Measures",
  "Difficult Choice",
  "Disappearance",
  "Disease Outbreak",
  "Environmental Disaster",
  "Escalation of Conflict",
  "Escape Plan Gone Wrong",
  "Ethical Dilemma",
  "Extinction Event",
  "False Accusation",
  "Family Feud",
  "Forbidden Knowledge",
  "Forbidden Love",
  "Forced Alliance",
  "Frame-Up",
  "Genetic Manipulation",
  "Hidden Weakness",
  "Historical Revisionism",
  "Identity Crisis",
  "Identity Theft",
  "Impending Doom",
  "Impossible Choice",
  "Inescapable Fate",
  "Infiltration Gone Awry",
  "Infiltration",
  "Information Control",
  "Inherited Responsibility",
  "Interdimensional Travel",
  "Invasion",
  "Kidnapping",
  "Legal Trouble",
  "Loss of Cultural Identity",
  "Lost Artifact",
  "Love Triangle",
  "Manipulation",
  "Mass Hysteria",
  "Mind Control",
  "Miscommunication",
  "Misguided Trust",
  "Misplaced Trust",
  "Mistaken Assumption",
  "Mistaken Identity",
  "Moral Dilemma",
  "Natural Disaster",
  "Natural Resource Depletion",
  "New Adversary",
  "Parallel Universe",
  "Personal Conflict",
  "Plan Failure",
  "Political Intrigue",
  "Power Struggle",
  "Power Vacuum",
  "Prophecy",
  "Quest for Redemption",
  "Race Against Time",
  "Rebellion",
  "Redemption Arc",
  "Resource Loss",
  "Revelation",
  "Revenge Plot",
  "Reversal of Fortune",
  "Rivalry",
  "Romantic Misunderstanding",
  "Sabotage",
  "Sacrifice",
  "Secret Society",
  "Stolen Identity",
  "Sudden Betrayal",
  "Sudden Illness",
  "Supernatural Curses",
  "Supernatural Phenomenon",
  "Technological Apocalypse",
  "Technological Singularity",
  "Technology Malfunction",
  "Time Loop",
  "Time Travel",
  "Trust Issues",
  "Unexpected Betrayal",
  "Unexpected Consequences",
  "Unexpected Discovery",
  "Unexpected Return",
  "Unexplained Phenomenon",
  "Unforeseen Consequences",
  "Unforeseen Obstacles",
  "Unrequited Love",
  "Unseen Enemy",
  "War",
]
