"use strict";

function getRandomFramingEvent()
{
  return getRandomElement(kFramingEvents);
}

const kFramingEvents = [
  "Alchemical breakthrough announcement",
  "Alien artifact deciphering",
  "Alien civilization contact",
  "Ancestral spirit communication",
  "Ancient relic excavation",
  "Artificial intelligence consciousness awakening",
  "Artificial intelligence rights declaration",
  "Astral projection research",
  "Celestial body landing",
  "Celestial body terraforming",
  "Celestial navigation system unveiling",
  "Cosmic consciousness meditation",
  "Cosmic energy harnessing",
  "Cosmic energy redistribution",
  "Cosmic entity communion",
  "Cosmic harmony concert",
  "Cryptic prophecy unveiling",
  "Divine anointing",
  "Divine intervention manifestation",
  "Dragon alliance formation",
  "Dream realm exploration",
  "Eldritch portal opening",
  "Elemental artifact discovery",
  "Elemental convergence",
  "Elemental harmony festival",
  "Elemental plane fusion",
  "Elemental realm integration",
  "Ethics debate",
  "Future civilization encounter",
  "Genetic enhancement announcement",
  "Ghostly visitation",
  "Heroic trial",
  "Interdimensional commerce treaty",
  "Interdimensional gateway maintenance",
  "Interdimensional gateway regulation",
  "Interdimensional portal activation",
  "Interdimensional trade agreement",
  "International trade fair",
  "Interstellar summit",
  "Kingdom festival",
  "Legendary artifact unveiling",
  "Legendary hero resurrection",
  "Lost civilization rediscovery",
  "Lunar eclipse festival",
  "Magical academy inauguration",
  "Magical creature sanctuary inauguration",
  "Multiverse gateway discovery",
  "Mythical beast sanctuary opening",
  "Mythical creature appearance",
  "Mythical realm protection treaty",
  "Parallel dimension migration",
  "Parallel universe discovery",
  "Parallel universe tourism",
  "Peace treaty signing",
  "Pirate king crowning",
  "Planar gateway activation",
  "Psychic powers research",
  "Royal coronation",
  "Spirit realm diplomacy",
  "Spirit world integration",
  "Spiritual pilgrimage",
  "Star system colonization announcement",
  "Starfall celebration",
  "Sunken city rediscovery",
  "Supernatural phenomenon investigation",
  "Technological innovation unveiling",
  "Technomagic breakthrough unveiling",
  "Time capsule opening ceremony",
  "Time dilation experiment",
  "Time loop investigation",
  "Time manipulation discovery",
  "Time-traveling anomaly",
  "Transdimensional peacekeeping mission",
  "Tribal council",
  "Underwater civilization diplomacy",
  "Underworld journey initiation",
  "Universal harmony celebration",
  "Universal harmony proclamation",
  "Universal language creation",
  "Virtual reality universe unveiling",
]
