"use strict";

function getRandomRace()
{
  return getRandomElement([
    "Dragonborn",
    "Dwarf",
    "Elf",
    "Gnome",
    "Half-elf",
    "Halfling",
    "Half-orc",
    "Human",
    "Tiefling",
    "Tabaxi / Cat-folk",
    "Harengon / Rabbit-folk",
    "Centaur",
  ]);
}

function getRandomGender()
{
  return getRandomElement([
    "Male",
    "Female",
  ]);
}

function getRandomAge()
{
  return getRandomElement([
    "Child",
    "Young Adult",
    "Adult",
    "Mature Adult",
    "Elder",
  ]);
}

function getRandomPhysique()
{
  return getRandomElement([
    "Athletic",
    "Slender",
    "Stocky",
    "Obese",
    "Muscular",
    "Toned",
    "Average",
  ]);
}

function getRandomSkintone()
{
  return getRandomGaussianElement([
    "Ghostly",
    "Light",
    "Average",
    "Tan",
    "Darkest",
  ]);
}

function getRandomHair()
{
  return getRandomElement([
    "Black",
    "Brown",
    "Light Brown",
    "Dark Brown",
    "Blonde",
    "Dirty Blonde",
    "Auburn",
    "Ginger",
    "Red",
    "Dark Red",
    "White",
    "Grey",
  ]) + ", " + getRandomElement([
    "Straight",
    "Curly",
    "Wavy",
    "Frizzy",
  ]) + ", " + getRandomElement([
    "Shoulder length",
    "Waist lenth",
    "Knee lenth",
    "Short shaved",
    "Short",
  ]) + ", " + getRandomElement([
    "Down",
    "In a high pony",
    "In a low pony",
    "In a braid",
    "In a bun",
    "In a side bun",
  ]) + ", " + getRandomElement([
    "Clean",
    "Dirty",
    "Graying",
    "Streaks of color natural or dyed",
    "Ornaments hairband clips etc",
  ]);
}

function getRandomEyes()
{
  return getRandomElement([
    "Amethyst",
    "Emerald",
    "Sapphire",
    "Ruby",
    "Topaz",
    "Opal",
    "Obsidian",
    "Crystal",
    "Jade",
    "Garnet",
    "Aquamarine",
    "Amber",
    "Silver",
    "Gold",
    "Brown",
    "Blue",
    "Green",
    "Hazel",
    "Amber",
    "Gray",
    "Black",
    "Dark Brown",
    "Light Brown",
    "Dark Blue",
    "Light Blue",
    "Dark Green",
    "Light Green",
    "Dark Hazel",
    "Light Hazel",
  ]);
}

function getRandomClass()
{
  return getRandomElement([
    "Barbarian",
    "Bard",
    "Cleric",
    "Druid",
    "Fighter",
    "Monk",
    "Paladin",
    "Ranger",
    "Rogue",
    "Sorcerer",
    "Warlock",
    "Wizard",
  ]);
}

function getRandomNpcDoing()
{
  return getRandomElement([
    "Building",
    "Celebrating ",
    "Chasing",
    "Communicating",
    "Creating",
    "Dying / wounded ",
    "Exploring",
    "Fleeing",
    "Gathering",
    "Hallucinating / Altered State",
    "Hunting / foraging",
    "In combat",
    "Journey / pilgrimage",
    "Learning",
    "Lost / exploring",
    "Marking territory",
    "Mating / courting",
    "Negotiating",
    "Patrolling / guarding",
    "Protecting",
    "Resting / camping",
    "Ritual / magic",
    "Sleeping",
    "Socializing",
    "Trapped / imprisoned",
    "Washing",
  ]);
}

function getRandomNpcFeature()
{
  return getRandomElement([
    "Armor plating",
    "Bald",
    "Birthmark",
    "Braided beard or hair",
    "Cloaks or capes",
    "Distinctive nose",
    "Distinctive posutre",
    "Elaborate embroidery intricate patterns",
    "Exceptionally beautiful",
    "Exceptionally ugly",
    "Eye patch",
    "Facial hair",
    "Fancy hat",
    "Flamboyant clothes",
    "Formal clothes",
    "Mask",
    "Missing fingers",
    "Missing limbs or digits",
    "Missing teeth",
    "Naked",
    "Nervous twitch",
    "Piercings",
    "Pronounced scar",
    "Ragged dirty clothes",
    "Rich fabrics exotic accessories",
    "Scars",
    "Symbolic insignias or crests",
    "Tattoos",
    "Tunic robe ceremonial garments",
    "Unusual body modifications",
    "Unusual eye color",
    "Unusual eye colors",
    "Unusual hair color",
    "Unusual hair colors",
    "Unusual hair styles",
    "Unusual skin color",
    "Unusual skin textures",
  ]);
}

function getRandomNickname()
{
  return getRandomElement([
    "Ace",
    "Sparky",
    "Blaze",
    "Shadow",
    "Luna",
    "Maverick",
    "Jazz",
    "Echo",
    "Cricket",
    "Goose",
    "Bubbles",
    "Dizzy",
    "Noodle",
    "Puddles",
    "Socks",
    "Rascal",
    "Whiskers",
    "Jinx",
    "Pipsqueak",
    "Snickerdoodle",
    "Twinkle",
    "Sprout",
    "Zigzag",
    "Doodlebug",
    "Wiggles",
    "Biscuit",
    "Giggles",
    "Poptart",
    "Cuddlebug",
    "Munchkin",
    "Squiggle",
    "Nibbles",
    "Jellybean",
    "Bumblebee",
    "Snickers",
    "Fluffy",
    "Pebbles",
    "Breezy",
    "Chipmunk",
    "Snuggles",
    "Bubblegum",
    "Cheeky",
    "Fuzzy",
    "Peanut",
    "Sprinkles",
    "Gummybear",
    "Button",
    "Squeaky",
    "Marshmallow",
    "Cupcake",
    "Sugarplum",
    "Daffodil",
    "Sunshine",
    "Rainbow",
    "Moonbeam",
    "Starlight",
    "Snowflake",
    "Firefly",
    "Butterfly",
    "Dragonfly",
    "Ladybug",
    "Sparrow",
    "Bluebell",
    "Clover",
    "Honeybee",
    "Tulip",
    "Pansy",
    "Poppy",
    "Petal",
    "Daisy",
    "Blossom",
    "Breeze",
    "Misty",
    "River",
    "Ocean",
    "Willow",
    "Cedar",
    "Cypress",
    "Maple",
    "Aspen",
    "Willow",
    "Hazel",
    "Ivy",
    "Holly",
    "Juniper",
    "Birch",
    "Acorn",
    "Rowan",
    "Thorn",
    "Fern",
    "Moss",
    "Lark",
    "Finch",
    "Robin",
    "Sparrow",
    "Starling",
    "Wren",
    "Hawk",
    "Falcon",
    "Eagle",
  ]);
}

function getRandomMood()
{
  return getRandomElement([
    "Aggravated",
    "Amused",
    "Angry",
    "Anxious",
    "Apathetic",
    "Bored",
    "Calm",
    "Cautious",
    "Confused",
    "Content",
    "Determined",
    "Disappointed",
    "Enraged",
    "Enthusiastic",
    "Excited",
    "Frustrated",
    "Fulfilled",
    "Giddy",
    "Grateful",
    "Guilty",
    "Happy",
    "Hesitant",
    "Hopeful",
    "Indifferent",
    "Inspired",
    "Irritated",
    "Jovial",
    "Joyful",
    "Lethargic",
    "Lonely",
    "Loving",
    "Melancholic",
    "Mellow",
    "Mournful",
    "Nervous",
    "Optimistic",
    "Overwhelmed",
    "Peaceful",
    "Pensive",
    "Playful",
    "Reflective",
    "Regretful",
    "Rejuvenated",
    "Relaxed",
    "Resentful",
    "Restless",
    "Sad",
    "Satisfied",
    "Sentimental",
    "Serene",
    "Somber",
    "Stressed",
    "Surprised",
    "Sympathetic",
    "Tense",
    "Thoughtful",
    "Touched",
    "Vexed",
    "Worried",
    "Zestful",
  ]);
}

function getRandomDisposition()
{
  return getRandomGaussianElement([
    "Attacking",
    "Hostile",
    "Unfriendly",
    "Neutral",
    "Friendly",
    "Curious",
    "Cautious",
    "Fearful",
  ]);
}

function getRandomNpcTrait()
{
  return getRandomElement([
    "Abrasive",
    "Adventurous",
    "Adventurous",
    "Ambitious",
    "Ambitious",
    "Apathetic",
    "Arrogant",
    "Careful",
    "Careless",
    "Cautious",
    "Cautious",
    "Charismatic",
    "Charming",
    "Closed-minded",
    "Compassionate",
    "Confident",
    "Considerate",
    "Content",
    "Conventional",
    "Courageous",
    "Courageous",
    "Cowardly",
    "Creative",
    "Creative",
    "Critical",
    "Cruel",
    "Curious",
    "Cynical",
    "Deceitful",
    "Dependent",
    "Dishonest",
    "Disloyal",
    "Dreamy",
    "Dull",
    "Efficient",
    "Emotional",
    "Energetic",
    "Extravagant",
    "Foolish",
    "Forgiving",
    "Friendly",
    "Generous",
    "Greedy",
    "Gruff",
    "Hardworking",
    "Helpless",
    "Honest",
    "Honest",
    "Hostile",
    "Humble",
    "Idealistic",
    "Impatient",
    "Inconsiderate",
    "Independent",
    "Inefficient",
    "Insecure",
    "Insightful",
    "Insincere",
    "Insincere",
    "Intelligent",
    "Kind-hearted",
    "Lazy",
    "Lazy",
    "Lethargic",
    "Loyal",
    "Loyal",
    "Mysterious",
    "Oblivious",
    "Open-minded",
    "Optimistic",
    "Optimistic",
    "Outgoing",
    "Patient",
    "Pessimistic",
    "Practical",
    "Practical",
    "Punctual",
    "Reliable",
    "Reliable",
    "Reserved",
    "Resourceful",
    "Selfish",
    "Sensitive",
    "Simple-minded",
    "Sincere",
    "Sincere",
    "Stoic",
    "Supportive",
    "Suspicious",
    "Tardy",
    "Thick-skinned",
    "Thrifty",
    "Timid",
    "Treacherous",
    "Trusting",
    "Unpredictable",
    "Unreliable",
    "Vengeful",
    "Wise",
    "Wise",
  ]);
}

function getRandomAlignment()
{
  return getRandomElement([
    "Lawful good",
    "Neutral good",
    "Chaotic good",
    "Lawful neutral",
    "True neutral",
    "Chaotic neutral",
    "Lawful evil",
    "Neutral evil",
    "Chaotic evil",
  ]);
}

function getRandomOccupation()
{
  return getRandomElement([
    "Abbess",
    "Abbot",
    "Acrobat",
    "Actor",
    "Advocate",
    "Alchemist",
    "Anchorite",
    "Animal handler",
    "Apothecary",
    "Archer",
    "Architect",
    "Archivist",
    "Aristocrat",
    "Armorer",
    "Artisan",
    "Artist",
    "Assassin",
    "Astrologer",
    "Baker",
    "Banker",
    "Barbarian",
    "Barber",
    "Bard",
    "Bargeman",
    "Barkeep",
    "Barmaid",
    "Beekeeper",
    "Beggar",
    "Bishop",
    "Blacksmith",
    "Boatman",
    "Boatwright",
    "Bodyguard",
    "Bookbinder",
    "Bookseller",
    "Bowman",
    "Bowyer",
    "Brewer",
    "Brick maker",
    "Bricklayer",
    "Brigand",
    "Brothel owner",
    "Buckle maker",
    "Builder",
    "Butcher",
    "Cabinetmaker",
    "Camp follower",
    "Caravan leader",
    "Carpenter",
    "Cartographer",
    "Chandler",
    "Chaplain",
    "Charioteer",
    "Charlatan",
    "Chatelaine",
    "Chef",
    "Chieftain",
    "Clergyman",
    "Cleric",
    "Clerk",
    "Clockmaker",
    "Clothier",
    "Cobbler",
    "Commander",
    "Concubine",
    "Cook",
    "Cooper",
    "Copyist",
    "Costermonger",
    "Counselor",
    "Courtesan",
    "Courtier",
    "Cowherd",
    "Crofter",
    "Crossbowman",
    "Cutler",
    "Dairymaid",
    "Dancer",
    "Diplomat",
    "Distiller",
    "Diver",
    "Diviner",
    "Doctor",
    "Domestic servant",
    "Druid",
    "Duenna",
    "Dyer",
    "Emperor",
    "Empress",
    "Engraver",
    "Explorer",
    "Falconer",
    "Farmer",
    "Ferryman",
    "Fighter",
    "Fisherman",
    "Fishmonger",
    "Fletcher",
    "Footman",
    "Footpad",
    "Forester",
    "Fortune teller",
    "Fowler",
    "Fruiterer",
    "Furrier",
    "Galley slave",
    "Gamekeeper",
    "Gardener",
    "General",
    "Gladiator",
    "Glassblower",
    "Glazier",
    "Glovemaker",
    "Goatherd",
    "Goldsmith",
    "Grain merchant",
    "Gravedigger",
    "Grocer",
    "Groom",
    "Guardsman",
    "Guildmaster",
    "Harem guard",
    "Harness maker",
    "Hay merchant",
    "Hayward",
    "Healer",
    "Hearthwitch",
    "Herald",
    "Herbalist",
    "Herder",
    "Hermit",
    "Highwayman",
    "Historian",
    "Horse-leech",
    "Housemaid",
    "Hunter",
    "Huntress",
    "Illuminator",
    "Infantryman",
    "Innkeeper",
    "Interpreter",
    "Inventor",
    "Jailer",
    "Jester",
    "Jeweler",
    "Jongleur",
    "Judge",
    "Juggler",
    "King",
    "Kitchen drudge",
    "Kitchen maid",
    "Knight",
    "Laborer",
    "Lacemaker",
    "Lady",
    "Lady in waiting",
    "Lady's maid",
    "Laundress",
    "Lawyer",
    "Librarian",
    "Limner",
    "Linguist",
    "Locksmith",
    "Longbowman",
    "Longshoreman",
    "Lord",
    "Luthier",
    "Maidservant",
    "Majordomo",
    "Man at arms",
    "Mason",
    "Masseur",
    "Mayor",
    "Mercer",
    "Merchant",
    "Messenger",
    "Midwife",
    "Miller",
    "Milliner",
    "Miner",
    "Minister",
    "Minstrel",
    "Moneylender",
    "Monk",
    "Mortician",
    "Mourner",
    "Musician",
    "Navigator",
    "Necromancer",
    "Noble",
    "Nun",
    "Nurse",
    "Old-clothes seller",
    "Ostler",
    "Page",
    "Painter",
    "Paladin",
    "Pariah",
    "Pastry cook",
    "Peasant",
    "Peddler",
    "Perfumer",
    "Philosopher",
    "Physician",
    "Pickpocket",
    "Pigkeeper",
    "Pikeman",
    "Pilgrim",
    "Pirate",
    "Plasterer",
    "Playwright",
    "Poet",
    "Potboy",
    "Potter",
    "Poulterer",
    "Priest",
    "Priestess",
    "Prince",
    "Princess",
    "Prior",
    "Prioress",
    "Privateer",
    "Professor",
    "Prostitute",
    "Pursemaker",
    "Queen",
    "Rag-picker",
    "Ranger",
    "Ratcatcher",
    "Reeve",
    "Roofer",
    "Ropemaker",
    "Royal advisor",
    "Rugmaker",
    "Ruler",
    "Saddler",
    "Sailor",
    "Scabbard maker",
    "Scavenger",
    "Scholar",
    "Scout",
    "Scrivener",
    "Scullery maid",
    "Sculptor",
    "Seamstress",
    "Seneschal",
    "Serf",
    "Servant",
    "Shaman",
    "Shearer",
    "Shepherd",
    "Ship's captain",
    "Shipwright",
    "Shoemaker",
    "Silversmith",
    "Singer",
    "Slave",
    "Slaver",
    "Smith",
    "Soldier",
    "Sorcerer",
    "Sorceress",
    "Spice merchant",
    "Spinner",
    "Spinster",
    "Sponge diver",
    "Spy",
    "Squire",
    "Stablehand",
    "Stevedore",
    "Steward",
    "Stonemason",
    "Storyteller",
    "Street kid",
    "Street seller",
    "Street sweeper",
    "Student",
    "Surgeon",
    "Surveyor",
    "Swineherd",
    "Swordsman",
    "Sycophant",
    "Tailor",
    "Tanner",
    "Tavernkeeper",
    "Tax collector",
    "Teacher",
    "Teamster",
    "Thatcher",
    "Thief",
    "Tinker",
    "Tollkeeper",
    "Torturer",
    "Town crier",
    "Toymaker",
    "Trapper",
    "Troubadour",
    "Tutor",
    "Vendor",
    "Vermin catcher",
    "Veterinarian",
    "Viking",
    "Village chief",
    "Vintner",
    "Warlock",
    "Warrior",
    "Water carrier",
    "Weaver",
    "Wetnurse",
    "Wheelwright",
    "Wine seller",
    "Witch",
    "Wizard",
    "Woodcarver",
    "Woodcutter",
    "Wool merchant",
    "Wrestler",
    "Writer",
  ]);
}

function getRandomNpcQuirk()
{
  return getRandomElement([
    "Biting into onions like an apple",
    "Eating loose tea leaves",
    "That they can fall asleep anywhere",
    "Eating ice",
    "Being able to play guitar behind their back",
    "Standing on chairs",
    "Sitting on chairs backwards",
    "Walking tiptoe",
    "Saying onomatopoeia out loud",
    "Commiting petty crime",
    "Tripping over their own feet when they run",
    "Moving their hands a lot while talking",
    "Thinking that they have god like abilities",
    "Leaning on things",
    "Reciting strange facts",
    "Trying to see if they can read upside down",
    "Knowing how to read upside down",
    "Trying to speak in reverse",
    "Not shutting up",
    "Using outdated slang terms yo",
    "Always wearing a hat no matter what",
    "Laughing for no reason",
    "That they constantly cry",
    "Not knowing how to read",
    "Having an obsession with the color red",
    "Smelling like low tide",
    "Constantly taking pictures of things",
    "Constantly writing various observations and events in a notebook",
    "Not having an indoor voice",
    "Being completely mediocre at everything they do",
    "Being overly competitive",
    "That they claim to be clairvoyant they aren't clairvoyant",
    "Hating the feeling of nail files",
    "Has a slight lisp",
    "Carries a lucky coin",
    "Snorts when laughing",
    "Always carries a book journal",
    "Is a night morning person",
    "Is constantly losing things",
    "Tends to use large and sometimes esoteric words",
    "Has a photographic memory",
    "Often tells white lies",
    "Dresses too formally for most occasions",
    "Apologizes for bumping into inanimate objects",
    "Hums or whistles anytime the conversation dies down",
    "Always wears a particular religious or magical symbol",
    "Corrects others habitually",
    "Always wears a hat or other head covering",
    "Addicted to something harmless",
    "Is an obsessive fan or follower",
    "Always carries a childhood trinket",
    "Often misspeaks common phrases",
    "Allergic asthmatic chronically ill",
    "Artistic dreamer delusional",
  ]);
}
