"use strict";

function getRandomObjective()
{
  return getRandomElement(kObjectives);
}

const kObjectives = [
  "Ascend the perilous mountain",
  "Awaken sleeping god",
  "Awaken the dormant power",
  "Banish the eternal darkness",
  "Banish the evil sorcerer",
  "Break ancient curse",
  "Break curse of eternal night",
  "Break enchanted mirror",
  "Cleanse the cursed land",
  "Collect celestial fragments",
  "Confront the ancient deity",
  "Confront the ancient demon",
  "Confront the ancient evil",
  "Confront the ancient guardian",
  "Confront the dark entity",
  "Confront the dark sorcerer",
  "Confront the dark sorceress",
  "Confront the fallen angel",
  "Confront the malevolent force",
  "Confront the malevolent spirit",
  "Confront the shadowy figure",
  "Conquer the enchanted forest",
  "Conquer the enemy stronghold",
  "Defeat evil overlord",
  "Defeat guardian of the gate",
  "Defeat immortal sorcerer",
  "Defeat mind-controlling entity",
  "Defeat the immortal enemy",
  "Defend against ancient titan",
  "Defend against celestial army",
  "Defend against cosmic entity",
  "Defend against demon horde",
  "Defend against dragon riders",
  "Defend against invading dragons",
  "Defend against shadow army",
  "Defend against spectral invasion",
  "Defend the ancient city",
  "Defend the ancient relic",
  "Defend the besieged city",
  "Defend the royal bloodline",
  "Defend the sacred artifact",
  "Defend the sacred grove",
  "Defend the sacred land",
  "Defend the sacred mountain",
  "Defend the sacred relic",
  "Defend the sacred shrine",
  "Defend the sacred temple",
  "Defend the sacred text",
  "Defend village from invaders",
  "Destroy the dark artifact",
  "Discover ancient prophecy",
  "Discover lost civilization",
  "Discover origin of magic",
  "Discover origin of universe",
  "Discover secret of immortality",
  "Discover source of madness",
  "Discover the ancient civilization",
  "Discover the forbidden knowledge",
  "Discover the lost civilization",
  "Enter the forbidden realm",
  "Eradicate the monstrous horde",
  "Escape from collapsing reality",
  "Escape from collapsing universe",
  "Escape from cursed book",
  "Escape from cursed carnival",
  "Escape from cursed mirror",
  "Escape from cursed painting",
  "Escape from dream world",
  "Escape from enchanted forest",
  "Escape from frozen time",
  "Escape from haunted mansion",
  "Escape from illusion",
  "Escape from labyrinth of time",
  "Escape from living maze",
  "Escape from living nightmare",
  "Escape from maze of illusions",
  "Escape from maze of mirrors",
  "Escape from prison",
  "Escape from sinking island",
  "Escape the enchanted forest",
  "Escape the haunted mansion",
  "Escape the infernal prison",
  "Escape the infernal realm",
  "Escape the labyrinthine maze",
  "Explore the ancient ruins",
  "Explore the forbidden forest",
  "Explore the forgotten realm",
  "Explore the forgotten temple",
  "Explore the mythical realm",
  "Explore uncharted ruins",
  "Expose corrupt official",
  "Expose the treacherous spy",
  "Exterminate the vile dragon",
  "Find cure for plague",
  "Find hidden paradise",
  "Find key to forbidden realm",
  "Find key to forgotten realm",
  "Find key to the abyss",
  "Find lost city of gold",
  "Find lost treasure",
  "Find path through living jungle",
  "Find path through shifting sands",
  "Find path to underworld",
  "Find source of eternal winter",
  "Find the elusive cure",
  "Find way out of labyrinth",
  "Find way out of twisted reality",
  "Find way through shifting dimensions",
  "Free enslaved spirits",
  "Free trapped souls",
  "Heal corrupted land",
  "Heal the ailing kingdom",
  "Hunt the elusive prey",
  "Liberate the captive princess",
  "Liberate the captive souls",
  "Liberate the enslaved people",
  "Liberate the oppressed people",
  "Liberate the oppressed souls",
  "Locate the hidden sanctuary",
  "Master ancient magic",
  "Master art of shapeshifting",
  "Master the ancient magic",
  "Navigate the astral plane",
  "Navigate the celestial realm",
  "Navigate the ethereal plane",
  "Navigate the spirit realm",
  "Navigate the treacherous waters",
  "Protect the ancient artifact",
  "Protect the ancient relic",
  "Protect the innocent villagers",
  "Protect the magical forest",
  "Protect the sacred ground",
  "Protect the sacred treasure",
  "Pursue the fleeing criminal",
  "Reclaim the stolen land",
  "Recover lost harmony",
  "Recover lost identity",
  "Recover lost melody",
  "Recover stolen dreams",
  "Recover stolen soul",
  "Recover the lost memory",
  "Rescue kidnapped heir",
  "Rescue the captured princess",
  "Restore balance of elements",
  "Restore cursed land",
  "Restore forgotten kingdom",
  "Restore lost memories",
  "Restore the balance of magic",
  "Restore the balance of nature",
  "Restore the balance of power",
  "Restore the corrupted kingdom",
  "Restore the corrupted land",
  "Restore the cursed kingdom",
  "Restore the faded glory",
  "Restore the fallen kingdom",
  "Restore the lost kingdom",
  "Retrieve ancient tome",
  "Retrieve dragon's egg",
  "Retrieve heart of the mountain",
  "Retrieve legendary weapon",
  "Retrieve lost identity",
  "Retrieve lost love",
  "Retrieve lost paradise",
  "Retrieve lost world",
  "Retrieve magical relic",
  "Retrieve soul from oblivion",
  "Retrieve soul from underworld",
  "Retrieve stolen artifact",
  "Retrieve stolen memories",
  "Retrieve stolen starlight",
  "Retrieve stolen time",
  "Retrieve the lost artifact",
  "Retrieve the sacred scroll",
  "Retrieve the stolen amulet",
  "Retrieve the stolen artifact",
  "Retrieve the stolen crystal",
  "Retrieve the stolen heirloom",
  "Retrieve the stolen idol",
  "Retrieve the stolen manuscript",
  "Retrieve the stolen relic",
  "Retrieve the stolen scepter",
  "Retrieve the stolen talisman",
  "Retrieve the stolen tome",
  "Retrieve the stolen treasure",
  "Return stolen magic",
  "Return stolen sunlight",
  "Seek the legendary treasure",
  "Solve murder mystery",
  "Solve mystery of disappearing ships",
  "Solve mystery of vanishing town",
  "Solve puzzle of the stars",
  "Solve riddle of the sphinx",
  "Solve the cryptic puzzle",
  "Stop clockwork army",
  "Stop dark ritual",
  "Stop demon invasion",
  "Stop invasion of chaos creatures",
  "Stop invasion of cosmic horrors",
  "Stop invasion of elemental spirits",
  "Stop invasion of giant insects",
  "Stop invasion of reality warpers",
  "Stop invasion of shadow creatures",
  "Stop invasion of shadow dragons",
  "Stop plague of nightmares",
  "Stop time from unraveling",
  "Stop time loop",
  "Stop war between gods",
  "Stop war between realms",
  "Stop world-ending prophecy",
  "Survive deadly trials",
  "Survive the cursed labyrinth",
  "Survive the deadly trap",
  "Survive the deadly wilderness",
  "Survive the haunted mansion",
  "Uncover hidden conspiracy",
  "Uncover secret of eternal youth",
  "Uncover secret society",
  "Uncover the ancient prophecy",
  "Uncover the dark prophecy",
  "Uncover the hidden agenda",
  "Uncover the hidden conspiracy",
  "Uncover the hidden power",
  "Uncover the hidden secret",
  "Uncover the hidden treasure",
  "Uncover the lost prophecy",
  "Uncover truth behind illusion",
  "Unite the warring factions",
  "Unite warring factions",
  "Unlock the ancient mystery",
  "Unlock the ancient prophecy",
  "Unlock the hidden chamber",
  "Unmask the hidden traitor",
  "Unmask the mysterious stranger",
  "Unmask the secret identity",
  "Unravel web of lies",
  "Unveil true ruler",
  "Vanquish the demonic horde",
]
