"use strict";

function getRandomTrapObject()
{
  return getRandomElement([
    "Lever",
    "Plinth",
    "Statue",
    "Pedestal",
    "Altar",
    "Torch",
    "Crystal",
    "Gemstone",
    "Mirror",
    "Painting",
    "Tapestry",
    "Book",
    "Scroll",
    "Glyph",
    "Rune",
    "Amulet",
    "Crown",
    "Ring",
    "Staff",
    "Sword",
    "Bow",
    "Arrow",
    "Shield",
    "Armor",
    "Medallion",
    "Chalice",
    "Urn",
    "Cauldron",
    "Anvil",
    "Scythe",
    "Ladder",
    "Rope",
    "Chain",
    "Trap",
    "Coffin",
    "Sarcophagus",
    "Crate",
    "Barrel",
    "Chest",
    "Coffer",
    "Bag",
  ]);
}

function getRandomTrapTrigger()
{
  return getRandomElement([
    "Touched",
    "Looked at",
    "Moved through",
    "Opened",
    "Stepped on",
    "Moved",
    "Sound",
    "Movement"
  ]);
}

function getRandomTrapEffect()
{
  return getRandomElement([
    "Acidic corrosion",
    "Age manipulation",
    "Animated enemy",
    "Antimagic field",
    "Astral projection",
    "Blades",
    "Body possession",
    "Boulder",
    "Charm",
    "Collapse",
    "Confusion",
    "Curse",
    "Darkness",
    "Dimensional rift",
    "Disease",
    "Disintegration",
    "Doors shut",
    "Electric shock",
    "Elemental damage",
    "Energy drain",
    "Energy redirection",
    "Fear",
    "Fire damage",
    "Flooding",
    "Floor collapses/illusion",
    "Forceful impact",
    "Gravity manipulation",
    "Ice damage",
    "Illusion",
    "Invisibility",
    "Light beam",
    "Lowering ceiling",
    "Magic nullification",
    "Memory alteration",
    "Memory erasure",
    "Mimic",
    "Mind control",
    "Mind reading",
    "Noise",
    "Object transmutation",
    "Paralysis",
    "Petrification",
    "Pit",
    "Planar shift",
    "Poison",
    "Polymorph",
    "Psychic",
    "Reality warp",
    "Repulsion",
    "Shadow",
    "Silence",
    "Size alteration",
    "Sleep",
    "Soul imprisonment",
    "Sound blast",
    "Spatial distortion",
    "Spears",
    "Telekinetic force",
    "Telepathic intrusion",
    "Teleportation",
    "Temporal anomaly",
    "Terrain alteration",
    "Time distortion",
    "Weather manipulation",
  ]);
}

function getRandomTrapSeverity()
{
  return getRandomElement([
    "Setback",
    "Dangerous",
    "Deadly",
  ]);
}
