"use strict";

function getRandomWildernessLocation()
{
  return getRandomElement([
    "Archipelago",
    "Avalanche",
    "Barrier island",
    "Basalt formation",
    "Beach",
    "Bluff",
    "Bog",
    "Boulder",
    "Brook",
    "Burrows",
    "Caldera",
    "Canyon",
    "Cape",
    "Carts",
    "Castle",
    "Cave",
    "Cavern",
    "Cliff",
    "Coast",
    "Coral atoll",
    "Coral reef",
    "Crater",
    "Crevasse",
    "Dam",
    "Delta",
    "Desert",
    "Drumlin",
    "Dune",
    "Esker",
    "Estuary",
    "Farm",
    "Fault line",
    "Fern",
    "Fissure",
    "Fjord",
    "Forest",
    "Fossil",
    "Frost heave",
    "Geothermal vent",
    "Glacier",
    "Gneiss formation",
    "Gorge",
    "Granite formation",
    "Hill",
    "Hot spring",
    "House",
    "Hovel",
    "Ice cave",
    "Ice sheet",
    "Iceberg",
    "Icefall",
    "Insect",
    "Island",
    "Jungle",
    "Karst landscape",
    "Kettle lake",
    "Knoll",
    "Lagoon",
    "Lake",
    "Landslide",
    "Lava dome",
    "Lava flow",
    "Lava tube",
    "Lichen",
    "Limestone formation",
    "Magma chamber",
    "Marble formation",
    "Marsh",
    "Meadow",
    "Monastery",
    "Moraine",
    "Moss",
    "Mountain",
    "Mountains",
    "Mushroom",
    "Oasis",
    "Ocean",
    "Path",
    "Peninsula",
    "Permafrost",
    "Petrified wood",
    "Plains",
    "Plateau",
    "Pond",
    "Pyroclastic flow",
    "Quartz formation",
    "Ravine",
    "Ridge",
    "River",
    "Rock",
    "Rockslide",
    "Ruins",
    "Sand dune",
    "Sandbar",
    "Sandstone formation",
    "Savanna",
    "Schist formation",
    "Seashell",
    "Shoal",
    "Shoreline",
    "Sinkhole",
    "Slate formation",
    "Spit",
    "Stream",
    "Swamp",
    "Temple",
    "Town",
    "Trails",
    "Tundra",
    "Valley",
    "Village",
    "Volcano",
    "Waterfall",
    "Wetland",
    "Wildflower",
  ]);
}
function getRandomWildernessTime()
{
  return getRandomElement([
    "Dawn",
    "Morning",
    "Noon",
    "Afternoon",
    "Dusk",
    "Evening",
    "Night",
    "Midnight",
  ]);
}

function getRandomWildernessTemperature()
{
  return getRandomGaussianElement([
    "Freezing",
    "Cold",
    "Below average",
    "Normal",
    "Above average",
    "Hot",
    "Sweltering",
  ]);
}

function getRandomWildernessWind()
{
  return getRandomGaussianElement([
    "Gale",
    "Gusty",
    "Breezy",
    "Calm",
    "Breezy",
    "Gusty",
    "Gale",
  ]);
}
function getRandomWildernessWeather()
{
  return getRandomGaussianElement([
    "Dust storm",
    "Tornado",
    "Hurricane",
    "Rainy",
    "Foggy",
    "Cloudy",
    "Sunny",
    "Overcast",
    "Hailstorm",
    "Stormy",
    "Thunderstorm",
    "Freezing rain",
    "Snowy",
    "Blizzard",
  ]);
}

function getRandomUrbanName()
{
  return "The " + getRandomAdjective() + " " + getRandomNoun();
}
function getRandomUrbanFeature()
{
  return getRandomElement([
    "A stranger leaves a box on their table",
    "A traveler",
    "About to host negotiations",
    "Actually a cult front",
    "Don't like outsiders",
    "Doubles as another business",
    "Drinks are a cure-all",
    "Famous pet",
    "Haunted",
    "High-class",
    "Hosting a passing mercenary company",
    "Hosts conspiracy meetings",
    "Intense rivalry with a competitor",
    "Is hosting a competition, but is short players",
    "Just one loooooong table",
    "Low-class",
    "Magic is being used",
    "Mystery fillings!",
    "Neglected and rundown",
    "No one around",
    "Optical illusions for fun",
    "Owner feeds of guests at night",
    "Peak time",
    "Pilgrimage site",
    "Repurposed from a temple/ship/observatory",
    "Seedy",
    "Was burgled/trashed last night",
    "Weapons are not allowed",
    "Workers are under control",
  ]);
}

function getRandomUrbanLocation()
{
  return getRandomElement([
    "Abandoned building",
    "Alchemist",
    "Apothecary",
    "Aqueduct",
    "Armory",
    "Baker",
    "Bakery",
    "Bathhouse",
    "Blacksmith",
    "Bridge",
    "Brothel",
    "Butcher",
    "Carpenter's workshop",
    "Castle",
    "Cathedral",
    "Cistern",
    "City gate",
    "City wall",
    "City well",
    "Dairy",
    "Dock",
    "Executioner's block",
    "Fishmonger",
    "Gallows",
    "Gatehouse",
    "Graveyard",
    "Guardhouse",
    "Guildhall",
    "Herb garden",
    "Herbalist",
    "Hospital",
    "Hovel",
    "Inn",
    "Jeweler's shop",
    "Manor house",
    "Market square",
    "Market stall",
    "Mason's workshop",
    "Mill",
    "Miller",
    "Monastery",
    "Pilgrims' hostel",
    "Pottery shop",
    "Rooftop",
    "School",
    "Scribe's shop",
    "Secret passage",
    "Sewer entrance",
    "Stable",
    "Stocks",
    "Street vendor",
    "Tailor's shop",
    "Tannery",
    "Tavern",
    "Town hall",
    "Town square",
    "Warehouse",
    "Watchtower",
    "Weaver",
    "Wharf",
  ]);
}
